//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emirhan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kullanicilar
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Lütfen Kullanýcý Adý Giriniz!")]
        public string kad { get; set; }
        [Required(ErrorMessage = "Lütfen Þifre Giriniz!")]
        public string sifre { get; set; }
        public virtual bool benihatirla { get; set; }
    }
}
