//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emirhan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eticaretEntities : DbContext
    {
        public eticaretEntities()
            : base("name=eticaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<elektronik> elektronik { get; set; }
        public DbSet<giyim> giyim { get; set; }
        public DbSet<kullanicilar> kullanicilar { get; set; }
        public DbSet<saataksesuar> saataksesuar { get; set; }
        public DbSet<sporoutdoor> sporoutdoor { get; set; }
    }
}
