//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emirhan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class saataksesuar
    {
        public int sid { get; set; }
        [Required]
        [Display(Name = "Baþlýk")]
        public string basllik { get; set; }
        [Required]
        [Display(Name = "Ürün Bilgi")]
        public string urunbilgi { get; set; }
        public string resim { get; set; }
        public virtual HttpPostedFileBase fotoFile { get; set; }
        public string kategori { get; set; }
        public int fiyat { get; set; }
        public bool aktifMi { get; set; }
        public Nullable<int> sira { get; set; }
    }
}
public enum kkkkategori
{
    Kadýn,
    Erkek,
    TakýMücevher
}
